### PR TITLE
Add README and Heroku deploy support

### PR DESCRIPTION
**Pull request by patcon**
This pull request adds some starter docs, pointing out how to get involved.

It also assumes that we auto-deploy to github, which I have happening on my
fork. Once merged, we'll need to make a few changes to have this same thing
happen on the main repo.

Let me know if you have any questions, or if I made any assumptions that don't
hold! Feel free to comment liberally with any changes you'd like to see!

### CODE REVIEW

**Comment by patcon** [comment]
oops. accidentally based this off @re-mint's branch. should i rebase off master, or is this fine to merge in anyhow? view results of this branch at: http://womenandcolor-frontend.herokuapp.com/#/

**Comment by patcon** [comment]
Thanks for feedback @re-mint!

1. re: yarn. i spent a lot of time philosophizing in other communities on the value of proper dependency resolution tools. Much of my thoughts ended up in [this essay written by a friend](https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527#b2d5) with whom I often tossed ideas around with. Main gist boils down to this:

**A given commit should always build the exact same site for everyone -- today for me, tomorrow for you, or some distant future for @emarchak3000, cyborg bounty-hunter.** If it doesn't do this then something is awry with the toolchain, and even if it doesn't do it by default, then it's a real big sign that the architects of the tool didn't care about something very important, and so probably built the tool with the wrong goals. (ie. npm) See https://circleci.com/blog/why-are-developers-moving-to-yarn/#yarnlock

We can put this out-of-scope of this PR, but in the end, this PR doesn't prevent you from using npm if you prefer -- it just helps people use yarn together if they feel it's the better tool. It doesn't hurt npm users, although sometimes they will build a broken or slightly different website, whereas yarn users will never hit that :)

**Comment by patcon** [comment]
re: heroku deployment. do you mean the code used to deploy to heroku looks different, or the website itself. screenshots are totally appreciated, so that we can work asynchronously in this issue without waiting to share screens next tues. thanks!

**Comment by patcon** [comment]
also, i'm seeing the exact same website locally and on heroku. might you have unpushed changes on your branch?

| heroku | localhost with `eric` branch |
|-----------|-------------|
| heroku screenshot | local screenshot

**Comment by re-mint** [comment]
I meant the code on heroku. The sidebar was stretched the entire width. I think it was a problem on the client side because it is rendering fine now.

**Comment by patcon** [comment]
Cool. Glad to hear. Anyhow, let me know what you feel needs to happen in order for this to get a :+1: review from you. If what I said about yarn didn't feel important, then just say so and I'll swap out that line :)

**Comment by patcon** [comment]
Ok rockin! I'll get the last bit of setup working soon. I'll create a new ticket to track that work, since I don't have time this moment :)

**Pull request merged**
